[package]
name = "rust_exercise_02"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenvy = "0.15.7"
helpers = "0.6.1"
serde = "1.0.228"
serde_json = "1.0.145"
uuid = "1.18.1"
uuid-extra = "0.0.2"
